"""Segmentation / Audience Builder metadata (see core-customer360/database-schema.sql:
``customer360.cdp_segments``).

One row per named segment tag -- the same tag strings that get written into
``cdp_master_profiles.segmentation_tags``. Stores the rule definition behind
a segment in two complementary forms (the raw jQuery QueryBuilder rule tree
in ``json_rules`` and its translated SQL fragment in ``sql_rules``), plus
``final_generated_sql``, the full query actually executed to (re)compute
segment membership. ``processed_by`` records whether the rules were authored
by a human via the QueryBuilder admin UI or generated by an AI agent.
"""

import uuid
from datetime import datetime
from typing import Any, Optional

from sqlalchemy import Boolean, ForeignKey, Integer, SmallInteger, Text, text
from sqlalchemy.dialects.postgresql import JSONB, TIMESTAMP
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from core.models.base import Base


class CdpSegment(Base):
    __tablename__ = "cdp_segments"

    segment_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True), ForeignKey("sys_tenant.tenant_id"), nullable=False
    )
    user_id: Mapped[Optional[uuid.UUID]] = mapped_column(PG_UUID(as_uuid=True), ForeignKey("sys_user.user_id"))
    domain: Mapped[str] = mapped_column(Text, nullable=False, server_default="all")

    segment_tag: Mapped[str] = mapped_column(Text, nullable=False)
    segment_name: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text)

    json_rules: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, server_default=text("'{}'::jsonb"))
    sql_rules: Mapped[Optional[str]] = mapped_column(Text)
    final_generated_sql: Mapped[Optional[str]] = mapped_column(Text)
    processed_by: Mapped[str] = mapped_column(Text, nullable=False, server_default="human")

    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("true"))
    member_count: Mapped[Optional[int]] = mapped_column(Integer, server_default="0")
    last_computed_at: Mapped[Optional[datetime]] = mapped_column(TIMESTAMP(timezone=False))

    created_at: Mapped[Optional[datetime]] = mapped_column(TIMESTAMP(timezone=False), server_default=text("now()"))
    updated_at: Mapped[Optional[datetime]] = mapped_column(TIMESTAMP(timezone=False), server_default=text("now()"))
    status_code: Mapped[int] = mapped_column(SmallInteger, server_default="1")
