package leotech.cdp.model.customer;

import java.util.Map;

import leotech.system.util.ReflectionUtil;

/**
 * SegmentType constants and utility mapping for the Customer Data Platform. <br>
 * Expanded to cover advanced Machine Learning, Streaming, Geofencing, and AI-driven Ad-Hoc Queries.
 * 
 * @author Trieu Nguyen
 * @since 2024
 */
public final class SegmentType {
	
	// ========================================================================
	// 1. TRADITIONAL QUERY TYPES
	// ========================================================================
	
	/**
	 * Run once for immediate reporting. Profiles are fetched, reported, and discarded.
	 */
	public static final int AD_HOC_QUERY = 0;
	
	/**
	 * Constantly updates as profiles meet or fail the AQL rules (e.g., "Users who logged in today").
	 */
	public static final int DYNAMIC = 1;
	
	/**
	 * A fixed list of profiles (CSV imports, manual tagging). Never changes unless manually updated.
	 */
	public static final int STATIC = 2;
	
	/**
	 * A mix of fixed profiles (Static) and rule-based queries (Dynamic).
	 */
	public static final int HYBRID = 3;


	// ========================================================================
	// 2. MACHINE LEARNING & PREDICTIVE AI
	// ========================================================================

	/**
	 * Segment populated automatically by a Churn Prediction ML model (e.g., "High Risk of Churn").
	 */
	public static final int PREDICTIVE_CHURN = 10;
	
	/**
	 * Segment populated by LTV (Lifetime Value) models (e.g., "Top 5% Future Value Customers").
	 */
	public static final int PREDICTIVE_CLV = 11;
	
	/**
	 * Profiles grouped by behavioral clustering algorithms (e.g., K-Means clustering for "Weekend Shoppers").
	 */
	public static final int ML_CLUSTERING = 12;
	
	/**
	 * Lookalike Audiences generated by analyzing an existing base and finding similar profiles.
	 */
	public static final int LOOKALIKE_AI = 13;
	
	/**
	 * Product Recommendation Segment: "Profiles likely to buy Product X next".
	 */
	public static final int NEXT_BEST_ACTION = 14;


	// ========================================================================
	// 3. REAL-TIME & STREAMING (MOMENT-OF-TRUTH)
	// ========================================================================

	/**
	 * Triggers instantly when an event streams into Kafka/Redis (e.g., "User abandoned cart 5 mins ago").
	 */
	public static final int REALTIME_EVENT_TRIGGER = 20;
	
	/**
	 * Profiles who cross a geographical boundary (e.g., "Walked into Mall Radius"). Requires mobile location data.
	 */
	public static final int GEOFENCE_PROXIMITY = 21;
	
	/**
	 * Profiles currently active/online on the website or mobile app RIGHT NOW.
	 */
	public static final int LIVE_SESSION_ACTIVE = 22;


	// ========================================================================
	// 4. GENERATIVE AI & NLP
	// ========================================================================

	/**
	 * An Ad-Hoc query built ENTIRELY by an LLM parsing natural language. 
	 * E.g., Marketer types: "Find all VIPs who complained last month but haven't bought since." 
	 * The AI agent maps it to this Segment Type to track that it was auto-generated.
	 */
	public static final int GEN_AI_PROMPT = 30;
	
	/**
	 * Segment generated based on NLP Sentiment Analysis of support tickets or reviews (e.g., "Angry Customers").
	 */
	public static final int NLP_SENTIMENT_NEGATIVE = 31;
	
	/**
	 * Segment generated based on NLP Sentiment Analysis (e.g., "Happy Brand Promoters").
	 */
	public static final int NLP_SENTIMENT_POSITIVE = 32;


	// -----------------------------------------------------------------------------------
	// CACHED REFLECTION MAPS (IMMUTABLE & THREAD-SAFE)
	// -----------------------------------------------------------------------------------
	
	private static final Map<Integer, String> VALUE_TO_NAME_MAP;
	private static final Map<String, Integer> NAME_TO_VALUE_MAP;

	static {
		// Java 10+ Map.copyOf() ensures strict Immutability for thread-safe global reads.
		VALUE_TO_NAME_MAP = Map.copyOf(ReflectionUtil.getConstantMap(SegmentType.class));
		NAME_TO_VALUE_MAP = Map.copyOf(ReflectionUtil.getConstantIntegerMap(SegmentType.class));
	}
	
	/**
	 * Private constructor to prevent accidental instantiation of utility class.
	 */
	private SegmentType() {
		throw new UnsupportedOperationException("Utility classes cannot be instantiated.");
	}
	
	/**
	 * Returns an unmodifiable map of Segment values to their string names.
	 * 
	 * @return Map<Integer, String>
	 */
	public static Map<Integer, String> getMapValueToName() {
		return VALUE_TO_NAME_MAP;
	}
	
	/**
	 * Safely retrieves the string name of the segment type.
	 * Useful for UI display and AI classification.
	 * 
	 * @param type the integer Segment type
	 * @return String name or "UNKNOWN" if not found
	 */
	public static String getTypeAsText(int type) {
		return VALUE_TO_NAME_MAP.getOrDefault(type, "UNKNOWN");
	}
	
	/**
	 * Safely retrieves the integer value of the segment type string.
	 * Allows an LLM or NLP pipeline to map string predictions back to database integers.
	 * 
	 * @param type the string Segment name (e.g., "GEN_AI_PROMPT")
	 * @return int value or 0 (AD_HOC_QUERY) if not found
	 */
	public static int getTypeAsInt(String type) {
		return NAME_TO_VALUE_MAP.getOrDefault(type, AD_HOC_QUERY);
	}
}