version: '3'
services:
  zookeeper3:
    image: zookeeper:3.4.14
    hostname: zookeeper3
    container_name: zookeeper3
    ports:
      - "${ZOOKEEPER3_IP:-127.0.0.1}:2183:2183"
    environment:
      ZOO_MY_ID: 3
      ZOO_PORT: 2183
      ZOO_SERVERS: server.3=${ZOOKEEPER3_IP:-127.0.0.1}:2888:3888
    volumes:
      - ./data/zookeeper3/data:/data
      - ./data/zookeeper3/datalog:/datalog